let resumeInfo = [
  {
    sectionTitle: "Education",
    title: "Devmountain",
    location: "Lehi, UT",
    startDate: null,
    endDate: null,
    graduationDate: "May 2022",
    jobTitle: null,
    project: null,
    details: ["16-week immersive Web Development Program"],
    projectLink: null,
    projectLinkTitle: null,
  },
  {
    sectionTitle: null,
    title: "Weber State University",
    location: "Ogden, UT",
    startDate: null,
    endDate: null,
    graduationDate: "Aug 2020 - Dec 2021",
    jobTitle: null,
    project: null,
    details: [
      "Associates Degree - General Studies",
      "Earned High Honor Roll during each semester at Weber State University",
    ],
    projectLink: null,
    projectLinkTitle: null,
  },
  {
    sectionTitle: "Professional Experience",
    title: "Justice Works, LLC",
    location: "Centerville, UT",
    startDate: "Aug 2022",
    endDate: "Current",
    graduationDate: null,
    jobTitle: "Web Developer I",
    project: null,
    details: [
      "Showed the ability to learn and apply new skills to efficiently complete tickets assigned to me.",
      "Used HTML, CSS, and Javascript to build functional components for the customer to use on a daily basis.",
      "Utilized problem-solving skills to produce creative solutions to tasks given to me.",
    ],
    projectLink: null,
    projectLinkTitle: null,
  },
  {
    sectionTitle: null,
    title: "Devmountain Student Developers",
    location: "Lehi, UT",
    startDate: "Feb 2022",
    endDate: "May 2022",
    graduationDate: null,
    jobTitle: "Web Developer / Software Engineer (student)",
    project: "Sell Monkey",
    details: [
      "Utilized ReactJS to develop an application allowing users to buy and sell used items.",
      "Protected user data with Auth0 for a secure way to log in to the application.",
      "Used Stripe to allow users to purchase items with debit or credit cards securely.",
    ],
    projectLink: "https://github.com/alexlamb10/sell-monkey",
    projectLinkTitle: "Sell Monkey Repo.",
  },
  {
    sectionTitle: null,
    title: null,
    location: null,
    startDate: null,
    endDate: null,
    graduationDate: null,
    jobTitle: null,
    project: "Trip Planner",
    details: [
      "Developed an application using Vanilla JS enabling users to keep track of desired vacation cities.",
      "Provided authentication and user credentials using Bcrypt to ensure each user’s profile security.",
      "Used AWS S3 allowing users to upload pictures to the database upon completing a pre-saved trip.",
    ],
    projectLink: "https://github.com/alexlamb10/devmountain-capstone-1",
    projectLinkTitle: "Trip Planner Repo.",
  },
  {
    sectionTitle: null,
    title: "America First Credit Union",
    location: "Ogden, UT",
    startDate: "Dec 2020",
    endDate: "Feb 2022",
    graduationDate: null,
    jobTitle: "Member Service Representative",
    project: null,
    details: [
      "Identified solutions for clients using active listening and company resources to improve company customer ratings.",
      "Informed clients of the company of resources available to them to enhance their personal banking, which saved the company and client time.",
      "Implemented new techniques to improve how I communicated with clients through training provided by the company in order to give each client a better experience.",
      "Worked on a team in which I strived to be uplifting to each of my coworkers in order for them to feel comfortable in the work environment each day.",
    ],
    projectLink: null,
    projectLinkTitle: null,
  },
  {
    sectionTitle: "Service/Leadership",
    title: "The Church of Jesus Christ of Latter-day Saints",
    location: "Port Vila, Vanuatu",
    startDate: "Aug 2018",
    endDate: "April 2020",
    graduationDate: null,
    jobTitle: "Full-Time Missionary",
    project: null,
    details: [
      "Worked as a service missionary for a period of 20 months.",
      "Strengthened leadership and communication skills as I oversaw multiple groups of other missionaries.",
      "Developed a strong work ethic as I worked 10 hours a day to meet personal goals.",
      "Became fluent in speaking, writing, and reading Bislama.",
    ],
    projectLink: null,
    projectLinkTitle: null,
  },
]

export default resumeInfo
